# Generated by Django 5.0.6 on 2024-06-11 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Icategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shelf_number', models.IntegerField()),
                ('purchase_id', models.IntegerField()),
                ('item', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('unit', models.IntegerField()),
                ('expiry_date', models.DateTimeField()),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
                ('price', models.IntegerField()),
                ('inventory_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.icategory')),
            ],
        ),
    ]
