# Generated by Django 5.0.6 on 2024-06-17 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='inventory',
            new_name='ainventory',
        ),
    ]
