# Generated by Django 5.0.6 on 2024-06-17 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rename_inventory_ainventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ainventory',
            name='unit',
            field=models.CharField(choices=[('L', 'Litres (L)'), ('mL', 'Millilitres (mL)'), ('g', 'Grams (g)'), ('kg', 'Kilograms (kg)'), ('packets', 'Packets')], max_length=20),
        ),
    ]
