# Generated by Django 5.0.6 on 2024-06-18 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_ainventory_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ainventory',
            name='entry_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ainventory',
            name='expiry_date',
            field=models.DateField(),
        ),
    ]
