# Generated by Django 5.0.6 on 2024-07-01 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_ainventory_entry_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ainventory',
            name='expiry_date',
            field=models.DateField(null=True),
        ),
    ]
