# Generated by Django 5.0.6 on 2024-07-01 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_ainventory_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ainventory',
            name='entry_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
