# Generated by Django 5.0.6 on 2024-07-01 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_ainventory_entry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ainventory',
            name='expiry_date',
            field=models.DateField(null=True),
        ),
    ]
