# Generated by Django 5.0.6 on 2024-06-16 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='menu',
            new_name='amenu',
        ),
    ]
