# Generated by Django 5.0.6 on 2024-06-15 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='POS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField()),
                ('Customer', models.CharField(max_length=50)),
                ('option_to_eat', models.CharField(max_length=50)),
            ],
        ),
    ]
