# Generated by Django 5.0.6 on 2024-06-17 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pos',
            name='option_to_eat',
            field=models.CharField(choices=[('dine_in', 'Dine In'), ('take_out', 'Take Out'), ('delivery', 'Delivery')], default='dine_in', max_length=50),
        ),
    ]
