# Generated by Django 5.0.6 on 2024-06-18 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_alter_pos_option_to_eat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pos',
            old_name='Customer',
            new_name='Customer_name',
        ),
        migrations.AddField(
            model_name='pos',
            name='Address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pos',
            name='Email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pos',
            name='Phone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pos',
            name='order_date',
            field=models.DateField(),
        ),
    ]
