# Generated by Django 5.0.6 on 2024-06-27 14:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_rename_menu_amenu'),
        ('pos', '0003_rename_customer_pos_customer_name_pos_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='pos',
            old_name='Address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='pos',
            old_name='Customer_name',
            new_name='customer_name',
        ),
        migrations.RenameField(
            model_name='pos',
            old_name='Email',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='pos',
            name='Phone',
        ),
        migrations.AlterField(
            model_name='pos',
            name='option_to_eat',
            field=models.CharField(choices=[('dine_in', 'Dine In'), ('take_out', 'Take Out'), ('delivery', 'Delivery')], default='dine_in', max_length=10),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('productorder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_carts', to='menu.amenu')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_carts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('canceled', 'Canceled')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_amount', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('total_price', models.FloatField(blank=True, null=True)),
                ('menuorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_ordered_items', to='menu.amenu')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='menu_order',
            field=models.ManyToManyField(through='pos.OrderItem', to='menu.amenu'),
        ),
        migrations.AddField(
            model_name='pos',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
