# Generated by Django 5.0.6 on 2024-06-27 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_rename_address_pos_address_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='POS',
        ),
    ]
