# Generated by Django 5.0.6 on 2024-07-02 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0005_delete_pos'),
    ]

    operations = [
        migrations.CreateModel(
            name='POS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField()),
                ('customer_name', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('option_to_eat', models.CharField(choices=[('dine_in', 'Dine In'), ('take_out', 'Take Out'), ('delivery', 'Delivery')], default='dine_in', max_length=10)),
            ],
        ),
    ]
